// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChartController from "./chart_controller"
application.register("chart", ChartController)

import DisplayController from "./display_controller"
application.register("display", DisplayController)

import InssDiscountController from "./inss_discount_controller"
application.register("inss-discount", InssDiscountController)

import NestedFormController from "./nested_form_controller"
application.register("nested-form", NestedFormController)

import PasswordToggleController from "./password_toggle_controller"
application.register("password-toggle", PasswordToggleController)

import RemoteModalController from "./remote_modal_controller"
application.register("remote-modal", RemoteModalController)
